In [1]:
###############################################################################
# Author: Saeed Rahman
# Date: 8/21/2019
# A simple SMA Strtategy to Backtest FX Strategy
###############################################################################

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import backtrader as bt
from datetime import datetime  
import cred
import btoandav20
import pytz
#Oanda Account Info
api_key = cred.token_prac
account_number = cred.acc_id_prac


In [2]:
# Create a Stratey
class TestStrategy(bt.Strategy):
    params = (
        ('maperiod', 45),
    )

    def log(self, txt, dt=None):
        ''' Logging function fot this strategy'''
        dt = dt or self.datas[0].datetime.date(0)
        tm= self.datas[0].datetime.time(0)
        # print('%s, %s' % (dt.isoformat(), txt))
        print(dt," ", tm," ",txt)

    def __init__(self):
        # Keep a reference to the "close" line in the data[0] dataseries
        self.dataclose = self.datas[0].close

        # To keep track of pending orders and buy price/commission
        self.order = None
        self.buyprice = None
        self.buycomm = None

        # Add a MovingAverageSimple indicator
        self.sma = bt.indicators.SimpleMovingAverage(
            self.datas[0], period=self.params.maperiod)

    def notify_order(self, order):
        if order.status in [order.Submitted, order.Accepted]:
            # Buy/Sell order submitted/accepted to/by broker - Nothing to do
            return

        # Check if an order has been completed
        # Attention: broker could reject order if not enough cash
        if order.status in [order.Completed]:
            if order.isbuy():
                self.log(
                    'BUY EXECUTED, Price: %.5f, Cost: %.2f, Comm %.2f' %
                    (order.executed.price,
                     order.executed.value,
                     order.executed.comm))

                self.buyprice = order.executed.price
                self.buycomm = order.executed.comm
            else:  # Sell
                self.log('SELL EXECUTED, Price: %.5f, Cost: %.2f, Comm %.2f' %
                         (order.executed.price,
                          order.executed.value,
                          order.executed.comm))

            self.bar_executed = len(self)

        elif order.status in [order.Canceled, order.Margin, order.Rejected]:
            self.log('Order Canceled/Margin/Rejected')

        self.order = None

    def notify_trade(self, trade):
        if not trade.isclosed:
            return

        self.log('OPERATION PROFIT, GROSS %.5f, NET %.2f' %
                 (trade.pnl, trade.pnlcomm))

    def next(self):
        print(datetime.now())
        # Simply log the closing price of the series from the reference
        self.log('Close, %.5f' % self.dataclose[0])

        # Check if an order is pending ... if yes, we cannot send a 2nd one
        if self.order:
            return

        # Check if we are in the market
        if not self.position:

            # Not yet ... we MIGHT BUY if ...
            if self.dataclose[0] > self.sma[0]:

                # BUY, BUY, BUY!!! (with all possible default parameters)
                self.log('BUY CREATE, %.5f' % self.dataclose[0])

                # Keep track of the created order to avoid a 2nd order
                self.order = self.buy()

        else:

            if self.dataclose[0] < self.sma[0]:
                # SELL, SELL, SELL!!! (with all possible default parameters)
                self.log('SELL CREATE, %.5f' % self.dataclose[0])

                # Keep track of the created order to avoid a 2nd order
                self.order = self.sell()

    def notify_data(self, data, status, *args, **kwargs):

        if status == data.LIVE:  # the data has switched to live data
           # do something
           pass



In [150]:
def load_db_credential_info(f_name_path):
    """
    load text file holding our database credential info and the database name
    args:
        f_name_path: name of file preceded with "\\", type string
    returns:
        array of 4 values that should match text file info
    """
    cur_path = os.getcwd()
    # lets load our database credentials and info
    f = open(cur_path + f_name_path, 'r')
    lines = f.readlines()[1:]
    lines = lines[0].split(',')
    return lines

In [154]:
import os
import bt_datafeed_postgres
db_info_file = "database_info.txt"
db_info_file_p = "/"+db_info_file
# necessary database info to connect
db_host, db_user, db_password, db_name = load_db_credential_info(db_info_file_p)
db_host, db_user, db_password, db_name = load_db_credential_info(db_info_file_p)
fromdate=datetime(2019,4,30)
todate=datetime(2019,6,5)
# data = bt.feeds.PandasData(dataname=df,timeframe=bt.TimeFrame.Days,openinterest=None)
data1 = bt_datafeed_postgres.PostgreSQL_Minute(dbHost=db_host,dbUser=db_user,dbPWD=db_password,dbName=db_name,ticker='EUR_USD',fromdate=fromdate,todate=todate)

Engine(postgresql+psycopg2://postgres:***@postgres_secmaster/securities_master)


In [155]:
# if __name__ == '__main__':
# Create a cerebro entity
cerebro = bt.Cerebro()

# Add a strategy
cerebro.addstrategy(TestStrategy)


oandastore = btoandav20.stores.OandaV20Store(token=api_key, account=account_number, practice=True)

cerebro.broker = oandastore.getbroker()

data = oandastore.getdata(
    dataname = "EUR_USD",
    timeframe = bt.TimeFrame.Minutes,
    compression=1,tz=pytz.timezone('US/Eastern'),
    backfill_from = data1
    # backfill_start=False, backfill=False
    # compression = 30,
#     fromdate = datetime(2018,11,1),
    # todate=datetime(2019,6,30)
    )

# Add data
cerebro.adddata(data)

print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())

cerebro.run()

print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())

# Add a FixedSize sizer according to the stake
cerebro.addsizer(bt.sizers.FixedSize, stake=1)

# Print out the starting conditions
print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())

# Run over everything
cerebro.run()

# Print out the final result
print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())

Starting Portfolio Value: 99952.63
position for instrument: EUR_USD


AttributeError: 'Lines_LineSeries_DataSeries_OHLC_OHLCDateTime_Abst' object has no attribute '_env'

In [ ]:
btoandav20.stores.abs

In [4]:
import numpy as np

In [10]:
np.array([0,1])+np.array([0,1])

array([0, 2])

In [6]:
np.add(np.array[0,1],np.array[0,1])

TypeError: 'builtin_function_or_method' object is not subscriptable

In [12]:
def factorial(x):
    return x*factorial(x-1) if x>1 else 1

In [82]:
A=np.array([[0,1],[1,0],[0,-1],[-1,0]])

In [35]:
np.random.randint(1, size=2)

array([0, 0])

In [49]:
np.random.choice(3, 1)

array([0])

In [72]:
B=A[np.random.choice(3, 1)]
B

array([[1, 0]])

In [78]:
start=np.array([[0,0]])

In [77]:
start+B

array([[1, 2]])

In [ ]:
def factorial(x):
    return x*factorial(x-1) if x>1 else 1

In [146]:
a=np.random.randint(40, size=4)
print(a)
print("The number of times you take a step in each direction")
b=np.array([[0,1],[1,0],[0,-1],[-1,0]])
print(b)
print("Possible steps in each direction")

[14 39 22 16]
The number of times you take a step in each direction
[[ 0  1]
 [ 1  0]
 [ 0 -1]
 [-1  0]]
Possible steps in each direction


In [147]:
c=a.reshape(-1,1)*b
c

array([[  0,  14],
       [ 39,   0],
       [  0, -22],
       [-16,   0]])

In [148]:
c.sum(axis=0)

array([23, -8])